# mkdocs.yml
site_name: Disciplina - Curso - IFRN
site_url: "https://lrlucena.github.io/disciplina"
site_description: "Site da disciplina"
repo_url: https://github.com/lrlucena/disciplina

theme:
  name: material
#  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top
  palette:
    primary: 'green'
    accent: 'yellow'
  logo: assets/images/logo-ifrn.png
  favicon: assets/images/favicon.png

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ifrn

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - git-revision-date-localized

nav:
  - Início: index.md
  - Programa da Disciplina: programa.md
  - Cronograma: cronograma.md
  - Materiais:
    - Aulas: materiais/aulas.md
    - Exercícios: materiais/exercicios.md
  - Avaliações: avaliacoes.md
  - Contato: contato.md